title: "DOROTHY AWINO ONGONGA"
email: ongongaawino614@gmail.com
description: >-
  Actuary | FULL STACK Software Developer | Graphic Designer | Data Scientist & ANALYST | AI & ML
baseurl: "" # don't change this for GitHub Pages
url: "https://dorothyawino.github.io" # your GitHub Pages URL
github_username: dorothyawino

# Theme
remote_theme: "mmistakes/minimal-mistakes"
minimal_mistakes_skin: "mint"

# Author details
author:
  name: "Dorothy Awino"
  avatar: "/assets/images/avatar.jpg" "C:\Users\Elite X2 G4\OneDrive\Pictures\ajira impact photo.jpg"
  bio: "Go Forth,Above and Beyond For Whatever You Desire Is Already In Existence"
  links:
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://linkedin.com/in/dorothyawino"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/dorothyawino"
    - label: "Email"
      icon: "fas fa-fw fa-envelope"
      url: "mailto:ongongaawino614@gmail.com"

# Footer links
footer:
  links:
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://linkedin.com/in/dorothyawino"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/dorothyawino"

# Markdown & Plugins
markdown: kramdown
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache
  - jekyll-seo-tag

# Pagination
paginate: 5
paginate_path: "/page:num/"

# Timezone (Optional but recommended)
timezone: Africa/Nairobi

# Output URL structure
permalink: /:categories/:title/

# Include folder for custom pages
include:
  - _pages

# Collections
collections:
  projects:
    output: true
    permalink: /projects/:name/

# Layout defaults
defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true
  - scope:
      path: "_projects"
      type: projects
    values:
      layout: single
      author_profile: true
      share: true

# Archive settings
category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/
